export const products = [
  {
    name: 'Whey Protein Isolate - Vanilla',
    slug: 'whey-protein-isolate-vanilla',
    description:
      'Premium cold-filtered whey protein isolate delivering 27g of pure protein per scoop with minimal fat and lactose. Perfect for muscle recovery and daily protein intake.',
    shortDesc: '27g protein per serving. Cold-filtered, ultra-pure.',
    price: 49.99,
    compareAtPrice: 64.99,
    images: [
      'https://images.unsplash.com/photo-1579722820308-d74e571900a9',
    ],
    category: 'Whey Protein',
    flavor: 'Vanilla',
    size: '2.2 lb (1000g)',
    weight: '1000g',
    proteinPerServing: 27,
    servingsPerContainer: 36,
    ingredients: 'Whey Protein Isolate, Natural Vanilla Flavor, Sunflower Lecithin',
    tags: ['best-seller', 'isolate', 'vanilla'],
    featured: true,
    inventory: 120,
  },
  {
    name: 'Whey Protein Isolate - Chocolate',
    slug: 'whey-protein-isolate-chocolate',
    description:
      'Rich, decadent chocolate flavored whey protein isolate. 27g protein, 1g fat, and zero sugar per scoop. Ideal for shakes, baking, and post-workout recovery.',
    shortDesc: '27g protein. Zero sugar. Decadent chocolate.',
    price: 49.99,
    compareAtPrice: 64.99,
    images: [
      'https://images.unsplash.com/photo-1516912481808-3406841bd33c',
    ],
    category: 'Whey Protein',
    flavor: 'Chocolate',
    size: '2.2 lb (1000g)',
    weight: '1000g',
    proteinPerServing: 27,
    servingsPerContainer: 36,
    ingredients: 'Whey Protein Isolate, Dutch Cocoa, Natural Chocolate Flavor, Stevia',
    tags: ['best-seller', 'isolate', 'chocolate'],
    featured: true,
    inventory: 140,
  },
  {
    name: 'Whey Protein Isolate - Strawberry',
    slug: 'whey-protein-isolate-strawberry',
    description:
      'Sweet, fruity strawberry whey protein isolate that mixes instantly. 27g of fast-digesting protein with a clean amino acid profile for optimal muscle building.',
    shortDesc: '27g protein. Fresh strawberry taste.',
    price: 49.99,
    compareAtPrice: 59.99,
    images: [
      'https://images.unsplash.com/photo-1600353588401-4b5974fc3d80',
    ],
    category: 'Whey Protein',
    flavor: 'Strawberry',
    size: '2.2 lb (1000g)',
    weight: '1000g',
    proteinPerServing: 27,
    servingsPerContainer: 36,
    ingredients: 'Whey Protein Isolate, Natural Strawberry Flavor, Beet Extract',
    tags: ['isolate', 'strawberry'],
    featured: false,
    inventory: 90,
  },
  {
    name: 'Casein Protein - Slow Release',
    slug: 'casein-protein-slow-release',
    description:
      'Micellar casein for slow-release protein throughout the night. 24g of protein that digests over 7-8 hours for maximum recovery while you sleep.',
    shortDesc: '24g slow-release protein. Perfect before bed.',
    price: 54.99,
    compareAtPrice: 69.99,
    images: [
      'https://images.unsplash.com/photo-1610701596007-11502861dcfa',
    ],
    category: 'Casein',
    flavor: 'Chocolate Peanut Butter',
    size: '2 lb (900g)',
    weight: '900g',
    proteinPerServing: 24,
    servingsPerContainer: 30,
    ingredients: 'Micellar Casein, Cocoa, Peanut Flour, Natural Flavors',
    tags: ['casein', 'night-time'],
    featured: true,
    inventory: 75,
  },
  {
    name: 'Vegan Plant Protein - Vanilla',
    slug: 'vegan-plant-protein-vanilla',
    description:
      'Complete plant-based protein blend of pea, brown rice, and hemp. 25g protein with all 9 essential amino acids. Vegan, gluten-free, and non-GMO.',
    shortDesc: '25g plant protein. Vegan & non-GMO.',
    price: 44.99,
    compareAtPrice: 54.99,
    images: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae',
    ],
    category: 'Plant Protein',
    flavor: 'Vanilla',
    size: '2.2 lb (1000g)',
    weight: '1000g',
    proteinPerServing: 25,
    servingsPerContainer: 33,
    ingredients: 'Pea Protein, Brown Rice Protein, Hemp Protein, Vanilla Extract',
    tags: ['vegan', 'plant-based'],
    featured: true,
    inventory: 60,
  },
  {
    name: 'Mass Gainer - Extreme 3000',
    slug: 'mass-gainer-extreme-3000',
    description:
      'High-calorie mass gainer with 50g protein and 3000 calories per serving. Engineered for hard gainers looking to pack on serious lean muscle mass.',
    shortDesc: '50g protein, 1250 calories per serving.',
    price: 59.99,
    compareAtPrice: 74.99,
    images: [
      'https://images.unsplash.com/photo-1594882645126-14020914d58d',
    ],
    category: 'Mass Gainer',
    flavor: 'Chocolate',
    size: '6 lb (2720g)',
    weight: '2720g',
    proteinPerServing: 50,
    servingsPerContainer: 16,
    ingredients: 'Whey Protein Concentrate, Maltodextrin, Oat Flour, Chocolate Powder',
    tags: ['mass-gainer', 'bulking'],
    featured: false,
    inventory: 45,
  },
  {
    name: 'Collagen Protein Powder',
    slug: 'collagen-protein-powder',
    description:
      'Hydrolyzed collagen peptides for skin, hair, nails, and joint health. 18g protein per scoop. Odorless, flavorless, and dissolves in any drink.',
    shortDesc: '18g collagen. Skin, hair & joint support.',
    price: 39.99,
    compareAtPrice: 49.99,
    images: [
      'https://images.unsplash.com/photo-1595348020949-87cdfbb44174',
    ],
    category: 'Collagen',
    flavor: 'Unflavored',
    size: '1.5 lb (680g)',
    weight: '680g',
    proteinPerServing: 18,
    servingsPerContainer: 34,
    ingredients: 'Hydrolyzed Collagen Peptides',
    tags: ['collagen', 'beauty', 'joints'],
    featured: false,
    inventory: 80,
  },
  {
    name: 'Pre-Workout Protein Bar Box',
    slug: 'pre-workout-protein-bar-box',
    description:
      'A box of 12 high-protein energy bars with 20g protein each. Perfect on-the-go snack with a perfect macro balance for sustained energy.',
    shortDesc: '20g protein per bar. 12 bars per box.',
    price: 29.99,
    compareAtPrice: 39.99,
    images: [
      'https://images.unsplash.com/photo-1610563166150-b34df4f3bcd6',
    ],
    category: 'Bars & Snacks',
    flavor: 'Assorted',
    size: '12 x 60g bars',
    weight: '720g',
    proteinPerServing: 20,
    servingsPerContainer: 12,
    ingredients: 'Whey Protein Crisps, Peanut Butter, Dates, Dark Chocolate',
    tags: ['bars', 'snacks', 'on-the-go'],
    featured: true,
    inventory: 200,
  },
  {
    name: 'Isolate + BCAAs Stack Bundle',
    slug: 'isolate-bcaas-stack-bundle',
    description:
      'Save with our ultimate protein bundle - 1 tub of whey isolate plus 30 servings of BCAAs for intra-workout fuel. Complete recovery stack.',
    shortDesc: 'Bundle: Whey isolate + 30 servings BCAA.',
    price: 69.99,
    compareAtPrice: 89.99,
    images: [
      'https://images.unsplash.com/photo-1593095948071-474c5cc2989d',
    ],
    category: 'Bundles',
    flavor: 'Vanilla / Blue Raspberry',
    size: '2.2 lb + 250g',
    weight: '1250g',
    proteinPerServing: 27,
    servingsPerContainer: 36,
    ingredients: 'Whey Protein Isolate, BCAA Complex (2:1:1)',
    tags: ['bundle', 'stack', 'value'],
    featured: false,
    inventory: 50,
  },
]

export const categories = [
  { name: 'All', slug: 'all' },
  { name: 'Whey Protein', slug: 'whey-protein' },
  { name: 'Casein', slug: 'casein' },
  { name: 'Plant Protein', slug: 'plant-protein' },
  { name: 'Mass Gainer', slug: 'mass-gainer' },
  { name: 'Collagen', slug: 'collagen' },
  { name: 'Bars & Snacks', slug: 'bars-and-snacks' },
  { name: 'Bundles', slug: 'bundles' },
]